#!/bin/bash

sleep 10

GREEN="\e[32m"
RED="\e[31m"
CYAN="\e[36m"
RESET="\e[0m"

SERVER_SESSION=$(screen -ls | grep -w server)

if [[ -z "$SERVER_SESSION" ]]; then
    echo -e "${RED}✖ Server is not running (crashed or stopped)${RESET}"
    killall screen >/dev/null 2>&1
else
    echo -e "${GREEN}✔ Server is running${RESET}"
fi

exit 0
